
CONTAINER_PADX = 8
CONTAINER_PADY = 8
DEFAULT_BORDERWIDTH = 1
FRAME_BORDERWIDTH = 6
DEFAULT_HEADERS = ('IP', 'Port', 'OS', 'Country', 'City')
LABEL_PADX = 6
LABEL_WIDTH = 6
BUTTON_PADX = 6
BUTTON_PADY = 6
LARGE_LABEL_WIDTH = 59
LARGE_LABEL_PADX = 6
